routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('administrator/login', ['uses' => 'Auth\AuthsController@getLogin'])->name('login');
Route::post('administrator/login', ['uses' => 'Auth\AuthsController@postLogin'])->name('login.post');
Route::post('administrator/register', ['uses' => 'Auth\AuthsController@postRegister'])->name('register');
Route::get('administrator/logout', ['uses' => 'Auth\AuthsController@getLogout'])->name('logout');
Route::get('user/activation/{token}', 'Auth\AuthsController@getActiveUser')->name('user.activate');
Route::post('user/forgot', 'Auth\AuthsController@postForgot')->name('user.forgot');
Route::get('/reset-password/{token}', 'Auth\AuthsController@getResetPassword')->name('user.reset');
Route::post('/reset-password', 'Auth\AuthsController@postResetPassword')->name('user.post-reset');

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => 'system'], function () {
        Route::resource('/dashboard', Administrators\Systems\DashboardController::class);
        Route::resource('branch', Systems\BranchesController::class);
        Route::resource('position', Systems\PositionsController::class);
        Route::get('user/user-department/{id}', 'Users\UsersController@getUserByDepartment')->name('user.list-user-by-department');
        Route::post('user/import', 'Users\UsersController@postImport')->name('user.import');
        Route::post('role/import', 'Permissions\RolesController@postImport')->name('role.import');
        Route::post('user/change-password', 'Users\UsersController@postChangePassword')->name('user.post-change-password');
        Route::get('/user/list', 'Users\UsersController@getList');
        Route::get('/user/change-password', 'Users\UsersController@getChangePassword')->name('user.get-change-password');
        Route::get('/user/be-managed', 'Users\UsersController@getBeManaged');
        Route::get('/user/search', 'Users\UsersController@getSearch');
        Route::get('user/student/edit-info', 'Users\EducationUserInfosController@index')->name('user.student.edit');
        Route::get('user/student/view-info/{id}', 'Users\EducationUserInfosController@viewInfo')->name('user.student.view');
        Route::get('user/student', 'Users\EducationUserController@index')->name('user.student');
        Route::get('user/teacher', 'Users\EducationUserController@getTeacher')->name('user.teacher');
        Route::get('user/teacher/view-info/{id}', 'Users\EducationUserInfosController@viewInfoTeacher')->name('user.teacher.view');
        Route::get('user/teacher/edit-info', 'Users\EducationUserInfosController@editInfoTeacher')->name('user.teacher.edit');
        Route::post('/user/{id}', 'Users\UsersController@destroy');
        Route::post('user/education-info/store', 'Users\EducationUserInfosController@store');
        Route::post('user/education-info/uploadavatar', 'Users\EducationUserInfosController@updateAvatar');
        Route::get('/user/read-notification/{id}', 'Users\UsersController@readNotification')->name('user.read.notification');
        Route::resource('user', Users\UsersController::class);
        Route::resource('department', Systems\DepartmentsController::class);
        Route::resource('company', Systems\CompaniesController::class);
        Route::resource('role', Permissions\RolesController::class);
        Route::resource('permission', Permissions\PermissionsController::class);
        Route::get('/config-role', 'Permissions\RolesController@getConfigRole')->name('role.config-role');
        Route::put('/put-permission', 'Permissions\RolesController@putPermissionIntoRole')->name('role.put-permission');
        Route::put('put-role', 'Permissions\RolesController@putRoleIntoUser')->name('role.put-role');
        Route::get('config-user', 'Permissions\RolesController@getConfigUser')->name('role.config-user');
        Route::get('config-role-user', 'Permissions\RolesController@getConfigRoleUser')->name('role.config-role-user');
        Route::post('config-role-user/store', 'Permissions\RolesController@postConfigRoleUser')->name('role.cf-role-user-store');
        Route::get('permission-by-role', 'Permissions\RolesController@getPermissionByRole');
        Route::resource('user-type', Users\TypesController::class);
    });
    Route::group(['prefix' => 'info'], function () {
        Route::post('/project/attachment', 'Projects\ProjectsController@postUploadAttachment')->name('project.upload-attachment');
        Route::get('/project/list', 'Projects\ProjectsController@getList');
        Route::post('/project/{id}', 'Projects\ProjectsController@update');
        Route::get('/project/delete/{id}', 'Projects\ProjectsController@destroy');
        Route::delete('/project/attachment', 'Projects\ProjectsController@postDeleteAttachment')->name('project.delete-attachment');
        Route::get('/project/city/{id}', 'Projects\ProjectsController@getDistrict');
        Route::resource('project-manager', Projects\ProjectManagersController::class);
        Route::resource('type', Projects\TypesController::class);
        Route::resource('segment', Projects\SegmentsController::class);
        Route::resource('project', Projects\ProjectsController::class);

        Route::resource('document-category', Projects\DocumentCategoriesController::class);
        Route::get('document/tree-data', 'Projects\DocumentsController@getTreeData')->name('document.tree-data');
        Route::get('document/upload/{id}', 'Projects\DocumentsController@getUpload')->name('document.upload');
        Route::resource('document', Projects\DocumentsController::class);
        Route::put('/news/accept/{id}', 'Projects\NewsController@putApprove')->name('news.approve');
    });
    Route::post('/upload', 'Administrators\Systems\UploadController@postUpload');

    Route::group(['prefix' => 'customer'], function () {
        Route::get('history/list/{id}', 'Customers\CustomersController@getHistoryToId')->name('customer.histories.list');
        Route::get('district/{id}', 'Customers\CustomersController@getDistrictOnCity')->name('city.district.list');
        Route::get('notification/call_back', 'Customers\CustomersController@listTimeCallBackCustomerOnday')->name('customer.notification.call_back');
        Route::get('project-by-sale/{id}', 'Customers\CustomersController@getProjectBySaleId')->name('customer.project.sale');
        // Thu hồi khách hàng
        Route::get('/list/{id}/collection-customer', 'Customers\CustomersController@collectionCustomer')->name('customer.collection-customer');
        Route::post('/list/{id}/update-collection-customer', 'Customers\CustomersController@updateCollectionCustomer')->name('customer.update-collection-customer');
        Route::get('/list/collection-customer', 'Customers\CustomerSharingUsersController@getCollectionCustomer')->name('customer.list-collection-customer');

        Route::get('upcoming/recover', 'Customers\CustomersController@getUpcomingRecover');
        Route::resource('list', Customers\CustomersController::class);
        Route::resource('level', Customers\LevelsController::class);
        Route::resource('customer_type', Customers\TypeCustomersController::class);
        Route::post('history/save', 'Customers\HistoriesController@saveHistory')->name('customer.history.save');
        Route::get('history/today/{type}', 'Customers\HistoriesController@getTodayCare');

        Route::get('/historyCus', 'Customers\CustomersController@historyCustomer')->name('customer.historyCus');
        Route::post('/getHistoryCus/{id}', 'Customers\CustomersController@getHistoryCustomer')->name('customer.getHistoryCus');
        Route::post('/showHistoryCus', 'Customers\CustomersController@showHistoryCustomer')->name('customer.showHistoryCus');

        Route::resource('history', Customers\HistoriesController::class);

        Route::get('/import', 'Customers\CustomersController@getImportForm')->name('customer.get-import');
        Route::post('/import', 'Customers\CustomersController@postImport')->name('customer.post-import');

        //giao thu contact
        Route::get('/share-customer-by-leader', 'Customers\CustomersController@getShareCustomerByLeader')->name('customer.get-share-customer-by-leader');
        Route::get('/get-total-customer-by-share/{id}', 'Customers\CustomersController@getTotalCustomerByShare')->name('customer.get-total-customer-by-share');
        Route::post('/share-customer-by-leader', 'Customers\CustomersController@postShareCustomerByLeader')->name('customer.post-share-customer-by-leader');


        Route::get('/import-store', 'Customers\CustomersController@getImportStoreForm')->name('customer_stores.get-import');
        Route::post('/import-store', 'Customers\CustomersController@postImportStore')->name('customer_stores.post-import');
        Route::get('/import-store/download-file', 'Customers\CustomersController@downloadFileImport')->name('customer_stores.download');
        Route::get('/stores', 'Customers\CustomersController@indexStores')->name('customer_stores.index');

        Route::post('/sharing/user-by-role/{id}', 'Customers\CustomerSharingsController@getUserByRole');

app/Http/Controllers/Administrators/Systems/DashboardController.php
<?php

namespace App\Http\Controllers\Administrators\Systems;

use App\Http\Controllers\Controller;
use App\Repositories\Administrators\Systems\DashboardRepository;

class DashboardController extends Controller {

    private $repository;

    // function __construct(DashboardRepository $repository) {
    //     $this->repository = $repository;
    // }

    public function index() {
        return view('administrator.dashboard');
    }

}

app/Http/Controllers/Administrators/Systems/UploadController.php
<?php

namespace App\Http\Controllers\Administrators\Systems;

use App\Http\Controllers\Controller;
use App\Services\AuthService;
use App\Services\ResponseService;
use Illuminate\Http\Request;

class UploadController extends Controller {
    private $auth;

    private $company;

    private $response;

    private $request;

    public function __construct(AuthService $auth, ResponseService $response, Request $request) {
        $this->auth     = $auth;
        $this->response = $response;
        $this->request  = $request;
    }

    public function postUpload() {
        $file            = $this->request->image;
        $destinationPath = public_path() . IMAGENEWS;
        $filename        = time() . '_' . $file->getClientOriginalName();
        $uploadSuccess   = $file->move($destinationPath, $filename);
        if ($uploadSuccess) {
            $upload = url(IMAGENEWS . $filename);
            return $this->response->json(true, $upload, trans('messages.upload_success'));
        }
        return $this->response->json(false, '', trans('messages.upload_failed'));
    }
}

app/Http/Controllers/Systems/DepartmentsController.php
<?php

namespace App\Http\Controllers\Systems;

use App\Models\Systems\Branch;
use App\Models\Systems\Company;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller as Controller;
use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\Systems\DepartmentCreateRequest;
use App\Http\Requests\Systems\DepartmentUpdateRequest;
use App\Repositories\Systems\DepartmentRepository;
use App\Validators\Systems\DepartmentValidator;

/**
 * Class DepartmentsController.
 *
 * @package namespace App\Http\Controllers\Systems;
 */
class DepartmentsController extends Controller
{
    /**
     * @var DepartmentRepository
     */
    protected $repository;

    /**
     * @var DepartmentValidator
     */
    protected $validator;

    private $partView;

    /**
     * DepartmentsController constructor.
     *
     * @param DepartmentRepository $repository
     * @param DepartmentValidator $validator
     */
    public function __construct(DepartmentRepository $repository, DepartmentValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
        $this->partView = 'administrator.systems.department';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $departments = $this->repository->paginate();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $departments,
            ]);
        }

        return view($this->partView.'.index', ['data' =>$departments]);
    }

    public function create(){
        $data['branch'] = Branch::all();
        $data['company'] = Company::all();
        return view($this->partView.'.create', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  DepartmentCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(DepartmentCreateRequest $request)
    {
        try {
            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $department = $this->repository->create($request->all());

            $response = [
                'message' => 'Thêm mới thành công.',
                'data'    => $department->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }
            return redirect()->route('department.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $department = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $department,
            ]);
        }

        return view('departments.show', compact('department'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->repository->find($id);
        $branch = Branch::all();
        $company = Company::all();
        return view('administrator.systems.department.edit', compact('data', 'branch', 'company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  DepartmentUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(DepartmentUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $department = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Department updated.',
                'data'    => $department->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }
            return redirect()->route('department.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Department deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Department deleted.');
    }
}

resources/views/administrator/systems/branch/create.blade.php
@extends('administrator.app')
@section('title','Chi nhánh')

@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                    Chi nhánh
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <div class="row">
            <div class="col-md-12" style="margin-bottom: 20px">
                <a href="{{ route('branch.index') }}" class="btn btn-success">Danh sách chi nhánh</a>
                <a href="{{ route('branch.create') }}" class="btn btn-primary">Thêm chi nhánh</a>
            </div>
            <div class="col-md-12">
                @include('administrator.errors.errors-validate')
                <!--begin::Portlet-->
                <div class="m-portlet m-portlet--tab">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Thêm mới chi nhánh
                                </h3>
                            </div>
                        </div>
                    </div>
                    {{ Form::open(array('route' => 'branch.store', 'class' => 'm-form m-form--fit m-form--label-align-right')) }}
                        <div class="m-portlet__body">
                            <div class="form-group m-form__group">
                                <label for="company_id">
                                    Công ty
                                </label>
                                <select class="form-control m-input" id="company_id" name="company_id">
                                    @foreach ($listCompany as $element)
                                        <option value="{{ $element['id'] }}">
                                            {{ $element['name'] }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group m-form__group">
                                <label for="name">
                                    Tên
                                </label>
                                <input type="name" class="form-control m-input" id="name" placeholder="Tên chi nhánh" name="name" value="{{ old('name') }}">
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__foot--fit">
                            <div class="m-form__actions">
                                <button class="btn btn-primary">
                                    Lưu
                                </button>
                                <a class="btn btn-secondary" href="{{ route('branch.index') }}">
                                    Trở về danh sách
                                </a>
                            </div>
                        </div>
                    {{-- </form> --}}
                    {{ Form::close() }}
                </div>
                <!--end::Portlet-->
            </div>
            <!--end::Form-->
        </div>
    </div>
</div>
@stop

resources/views/administrator/systems/branch/edit.blade.php
@extends('administrator.app')
@section('title','Chi nhánh')

@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
	<!-- BEGIN: Subheader -->
	<div class="m-subheader">
	    <div class="d-flex align-items-center">
	        <div class="mr-auto">
	            <h3 class="m-subheader__title m-subheader__title--separator">
	                Chi nhánh
	            </h3>
	            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
	                <li class="m-nav__item m-nav__item--home">
	                    <a href="#" class="m-nav__link m-nav__link--icon">
	                        <i class="m-nav__link-icon la la-home"></i>
	                    </a>
	                </li>
	            </ul>
	        </div>
	    </div>
	</div>
	<!-- END: Subheader -->
	<div class="m-content">
		<div style="margin-bottom: 20px">
			<a href="{{ route('branch.index') }}" class="btn btn-success">Danh sách chi nhánh</a>
        	<a href="{{ route('branch.create') }}" class="btn btn-primary">Thêm chi nhánh</a>
		</div>
		<div class="row">
	        <div class="col-md-12">
	            <!--begin::Portlet-->
				@include('administrator.errors.errors-validate')
	            <div class="m-portlet m-portlet--tab">
	                <div class="m-portlet__head">
	                    <div class="m-portlet__head-caption">
	                        <div class="m-portlet__head-title">
	                            <span class="m-portlet__head-icon m--hide">
	                                <i class="la la-gear"></i>
	                            </span>
	                            <h3 class="m-portlet__head-text">
	                                Cập nhật chi nhánh
	                            </h3>
	                        </div>
	                    </div>
	                </div>
	                {{ Form::open(array('route' => array('branch.update', $data->id), 'method' => 'PUT', 'class' => 'm-form m-form--fit m-form--label-align-right')) }}
	                    <div class="m-portlet__body">
	                    	<div class="form-group m-form__group">
                                <label for="company_id">
                                    Công ty
                                </label>
                                <select class="form-control m-input" id="company_id" name="company_id">
                                    @foreach ($listCompany as $element)
                                        <option value="{{ $element['id'] }}" {{ ($data->company_id == $element['id']) ? 'selected' : '' }}>
                                            {{ $element['name'] }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
	                        <div class="form-group m-form__group">
	                            <label for="name">
	                                Tên
	                            </label>
	                            <input type="name" class="form-control m-input" id="name" placeholder="Tên chi nhánh" name="name" value="{{ $data->name }}">
	                        </div>
	                    </div>
	                    <div class="m-portlet__foot m-portlet__foot--fit">
	                        <div class="m-form__actions">
	                            <button class="btn btn-primary">
	                                Lưu
	                            </button>
	                            <a class="btn btn-secondary" href="{{ route('branch.index') }}">
	                                Trở về danh sách
	                            </a>
	                        </div>
	                    </div>
	                {{-- </form> --}}
	                {{ Form::close() }}
	            </div>
	            <!--end::Portlet-->
	        </div>
	        <!--end::Form-->
	    </div>
	</div>
</div>
@stop

resources/views/administrator/systems/branch/index.blade.php
@extends('administrator.app')
@section('title','Chi nhánh')

@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                    Chi nhánh
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <!--begin::Section-->
        <div class="col-xs-12" style="margin-bottom: 20px">
            <a href="{{ route('branch.create') }}" class="btn btn-primary m-btn m-btn--icon">
                <span>
                    <i class="fa flaticon-plus"></i>
                    <span>
                        Thêm mới
                    </span>
                </span>
            </a>
        </div>
        @include('administrator.errors.info-search')
        <div class="m-section">
            @include('administrator.errors.messages')
            <div class="m-section__content">
                <table class="table m-table m-table--head-bg-warning">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Tên
                            </th>
                            <th>
                                Tùy chọn
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($data as $key => $value)
                        <tr>
                            <th scope="row">
                                {{ $key + 1 }}
                            </th>
                            <td>
                                <a href="#" id="username" data-type="text" data-pk="1" data-url="/post" data-title="Enter username">{{ $value['name'] }}</a>
                            </td>
                            <td>
                                <a href="{{ route('branch.edit', $value->id) }}" class="btn btn-accent m-btn m-btn--icon m-btn--icon-only">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                {{ Form::open(array('method'=>'DELETE', 'route' => array('branch.destroy', $value->id), 'style' => 'display: inline-block;')) }}
                                <button onclick="return confirm('Bạn có chắc chắn muốn xóa?');" class="btn btn-danger m-btn m-btn--icon m-btn--icon-only">
                                    <i class="fa fa-close"></i>
                                </button>
                                {{ Form::close() }}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            {{ $data->links() }}
            Tổng số {{ $data->total() }} bản ghi
        </div>
        <!--end::Section-->
    </div>
</div>
@stop