routes/web.php
        Route::get('user/teacher/view-info/{id}', 'Users\EducationUserInfosController@viewInfoTeacher')->name('user.teacher.view');
        Route::get('user/teacher/edit-info', 'Users\EducationUserInfosController@editInfoTeacher')->name('user.teacher.edit');
        Route::post('/user/{id}', 'Users\UsersController@destroy');
        Route::post('user/education-info/store', 'Users\EducationUserInfosController@store');
        Route::post('user/education-info/uploadavatar', 'Users\EducationUserInfosController@updateAvatar');
        Route::get('/user/read-notification/{id}', 'Users\UsersController@readNotification')->name('user.read.notification');
        Route::resource('user', Users\UsersController::class);
        Route::resource('department', Systems\DepartmentsController::class);
        Route::resource('company', Systems\CompaniesController::class);
        Route::resource('role', Permissions\RolesController::class);
        Route::resource('permission', Permissions\PermissionsController::class);
        Route::get('/config-role', 'Permissions\RolesController@getConfigRole')->name('role.config-role');
        Route::put('/put-permission', 'Permissions\RolesController@putPermissionIntoRole')->name('role.put-permission');
        Route::put('put-role', 'Permissions\RolesController@putRoleIntoUser')->name('role.put-role');
        Route::get('config-user', 'Permissions\RolesController@getConfigUser')->name('role.config-user');
        Route::get('config-role-user', 'Permissions\RolesController@getConfigRoleUser')->name('role.config-role-user');
        Route::post('config-role-user/store', 'Permissions\RolesController@postConfigRoleUser')->name('role.cf-role-user-store');
        Route::get('permission-by-role', 'Permissions\RolesController@getPermissionByRole');
        Route::resource('user-type', Users\TypesController::class);
    });
    Route::group(['prefix' => 'info'], function () {
        Route::post('/project/attachment', 'Projects\ProjectsController@postUploadAttachment')->name('project.upload-attachment');
        Route::get('/project/list', 'Projects\ProjectsController@getList');
        Route::post('/project/{id}', 'Projects\ProjectsController@update');
        Route::get('/project/delete/{id}', 'Projects\ProjectsController@destroy');
        Route::delete('/project/attachment', 'Projects\ProjectsController@postDeleteAttachment')->name('project.delete-attachment');
        Route::get('/project/city/{id}', 'Projects\ProjectsController@getDistrict');
        Route::resource('project-manager', Projects\ProjectManagersController::class);
        Route::resource('type', Projects\TypesController::class);
        Route::resource('segment', Projects\SegmentsController::class);
        Route::resource('project', Projects\ProjectsController::class);

        Route::resource('document-category', Projects\DocumentCategoriesController::class);
        Route::get('document/tree-data', 'Projects\DocumentsController@getTreeData')->name('document.tree-data');
        Route::get('document/upload/{id}', 'Projects\DocumentsController@getUpload')->name('document.upload');
        Route::resource('document', Projects\DocumentsController::class);
        Route::put('/news/accept/{id}', 'Projects\NewsController@putApprove')->name('news.approve');
    });
    Route::post('/upload', 'Administrators\Systems\UploadController@postUpload');

    Route::group(['prefix' => 'customer'], function () {
        Route::get('history/list/{id}', 'Customers\CustomersController@getHistoryToId')->name('customer.histories.list');
        Route::get('district/{id}', 'Customers\CustomersController@getDistrictOnCity')->name('city.district.list');
        Route::get('notification/call_back', 'Customers\CustomersController@listTimeCallBackCustomerOnday')->name('customer.notification.call_back');
        Route::get('project-by-sale/{id}', 'Customers\CustomersController@getProjectBySaleId')->name('customer.project.sale');
        // Thu hồi khách hàng
        Route::get('/list/{id}/collection-customer', 'Customers\CustomersController@collectionCustomer')->name('customer.collection-customer');
        Route::post('/list/{id}/update-collection-customer', 'Customers\CustomersController@updateCollectionCustomer')->name('customer.update-collection-customer');
        Route::get('/list/collection-customer', 'Customers\CustomerSharingUsersController@getCollectionCustomer')->name('customer.list-collection-customer');

        Route::get('upcoming/recover', 'Customers\CustomersController@getUpcomingRecover');
        Route::resource('list', Customers\CustomersController::class);
        Route::resource('level', Customers\LevelsController::class);
        Route::resource('customer_type', Customers\TypeCustomersController::class);
        Route::post('history/save', 'Customers\HistoriesController@saveHistory')->name('customer.history.save');
        Route::get('history/today/{type}', 'Customers\HistoriesController@getTodayCare');

        Route::get('/historyCus', 'Customers\CustomersController@historyCustomer')->name('customer.historyCus');
        Route::post('/getHistoryCus/{id}', 'Customers\CustomersController@getHistoryCustomer')->name('customer.getHistoryCus');
        Route::post('/showHistoryCus', 'Customers\CustomersController@showHistoryCustomer')->name('customer.showHistoryCus');

        Route::resource('history', Customers\HistoriesController::class);

        Route::get('/import', 'Customers\CustomersController@getImportForm')->name('customer.get-import');
        Route::post('/import', 'Customers\CustomersController@postImport')->name('customer.post-import');

        //giao thu contact
        Route::get('/share-customer-by-leader', 'Customers\CustomersController@getShareCustomerByLeader')->name('customer.get-share-customer-by-leader');
        Route::get('/get-total-customer-by-share/{id}', 'Customers\CustomersController@getTotalCustomerByShare')->name('customer.get-total-customer-by-share');
        Route::post('/share-customer-by-leader', 'Customers\CustomersController@postShareCustomerByLeader')->name('customer.post-share-customer-by-leader');


        Route::get('/import-store', 'Customers\CustomersController@getImportStoreForm')->name('customer_stores.get-import');
        Route::post('/import-store', 'Customers\CustomersController@postImportStore')->name('customer_stores.post-import');
        Route::get('/import-store/download-file', 'Customers\CustomersController@downloadFileImport')->name('customer_stores.download');
        Route::get('/stores', 'Customers\CustomersController@indexStores')->name('customer_stores.index');

        Route::post('/sharing/user-by-role/{id}', 'Customers\CustomerSharingsController@getUserByRole');
        Route::post('/sharing/count-customer', 'Customers\CustomerSharingsController@countCustomer');
        Route::get('/sharing/list', 'Customers\CustomerSharingsController@list')->name('sharing.list');
        Route::get('/sharing/sharing-user/{id}', 'Customers\CustomerSharingsController@getSharingUser')->name('sharing.list-user');
        Route::resource('sharing', Customers\CustomerSharingsController::class);
        Route::get('sharing-user/list-cus-share/{id}', 'Customers\CustomerSharingUsersController@listShare')->name('sharing-user.listShare');
        Route::get('sharing-user/list-cus-recovery/{id}', 'Customers\CustomerSharingUsersController@listRecovery')->name('sharing-user.listRecovery');
        Route::resource('sharing-user', Customers\CustomerSharingUsersController::class);


    });
    Route::get('fanpage', 'FacebooksController@getFanpage');
    Route::get('fanpage/post/{id}', 'FacebooksController@getPostByPage')->name('page.post');
    Route::get('fanpage/post/{id}/comments', 'FacebooksController@getCommentByPost')->name('page.post_comment');
    Route::get('fanpage/{pageId}/inbox', 'FacebooksController@getInboxByPage')->name('page.inbox');
    Route::get('fanpage/conversation/{conversationId}', 'FacebooksController@getConversationDetail')->name('page.conversation');

    Route::get('fanpage/find/{url}', 'FacebooksController@getPageByUrl');
    Route::get('fanpage/{pageId}/feed', 'FacebooksController@getFeedsByPage');
    Route::post('fanpage/{pageId}/feed', 'FacebooksController@postFeedToPage');
    Route::post('fanpage/post/{id}', 'FacebooksController@postCommentToPost');
    Route::get('fanpage/conversation/{conversationId}/reply', 'FacebooksController@postCommentToConversation');
    Route::get('fanpage/comments/{commentId}', 'FacebooksController@getCommentChild')->name('comment.child');
    Route::group(['prefix' => 'job'], function () {
        Route::post('report/evaluate/{id}', 'Jobs\ReportsController@postEvaluate')->name('report.evaluate');
        Route::post('task/stability-rate/{id}', 'Jobs\TasksController@postStabilityRate')->name('task.stability-rate');
        Route::post('task/suddenly-rate/{id}', 'Jobs\TasksController@postSuddenlyRate')->name('task.suddenly-rate');
        Route::post('report/approve/{id}', 'Jobs\ReportsController@postApprove')->name('report.approve');
        Route::get('dashboard', 'Jobs\ReportsController@getDashboard')->name('report.statistic');
        Route::get('report/task-suddenly/{type}', 'Jobs\ReportsController@getTaskSuddenly');

        Route::get('report/customer-by-week', 'Jobs\ReportsController@getReportCustomerByWeek')->name('report.customer-by-week');
        Route::get('report/customer-potential-by-project', 'Jobs\ReportsController@getReportCustomerPotentialByProject')->name('report.customer-potential-by-project');
        Route::resource('task', Jobs\TasksController::class);
        Route::resource('target', Jobs\PlansController::class);
        Route::post('/report/{id}', 'Jobs\ReportsController@update');
        Route::get('/export/{type}', 'Jobs\ReportsController@exportReport')->name('report.export');
        Route::get('/report-trial', 'Jobs\ReportsController@indexTrialPeriod')->name('report-trial.index');

app/Http/Controllers/Apis/Customers/BookingViewController.php
<?php

namespace App\Http\Controllers\Apis\Customers;

use App\Models\Customers\BookingViewHouse;
use App\Services\ResponseService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class BookingViewController extends Controller
{
    private $request;
    private $account;
    private $model;
    private $response;
    public function __construct(Request $request, BookingViewHouse $consignments, ResponseService $response)
    {
        $this->request = $request;
        $this->account = Auth::guard('api')->user();
        $this->model   = $consignments;
        $this->response= $response;
    }

    public function store(){
        $input = $this->request->all();
        $input[$this->model::ACCOUNT_ID] = $this->account->id;
        $rules = [
            'fullname' => 'required',
            'phone' => 'required',
            'email' => 'required',
            'time_view' => 'required',
            'note' => 'required',
        ];
        $validator = validateInput($input, $rules, []);
        if ($validator) {
            return $this->response
                ->json(CODE_NO_ACCESS, $validator->getMessageBag(), trans('messages.something_went_wrong'));
        }
        $result = BookingViewHouse::create($input);
//        dd($input);
        if($result){
            return $this->response->json(CODE_SUCCESS, '', trans('messages.create_success'));
        }else{
            return $this->response->json(CODE_NO_ACCESS, '', trans('messages.create_failed'));
        }
    }
}

app/Http/Controllers/Apis/Customers/ConsignmentController.php
<?php

namespace App\Http\Controllers\Apis\Customers;

use App\Models\Customers\Consignments;
use App\Models\Customers\OptionConsignments;
use App\Models\Projects\District;
use App\Models\Projects\Province;
use App\Services\ResponseService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ConsignmentController extends Controller
{
    private $request;
    private $account;
    private $model;
    private $response;
    public function __construct(Request $request, Consignments $consignments, ResponseService $response)
    {
        $this->request = $request;
        $this->account = Auth::guard('api')->user();
        $this->model   = $consignments;
        $this->response= $response;
    }
    public function index(){
        $data = $this->model->where('account_id', $this->account->id)->orderBy('id', 'desc')->get();
        return $this->response->json(CODE_SUCCESS, $data, '');
    }

    public function storage(){
        $input = $this->request->all();
        $rules = [
            'fullname' => 'required',
            'phone' => 'required',
            'email' => 'required',
            'title' => 'required',
            'product_type' => 'required',
            'land_type' => 'required',
            'address' => 'required',
            'city_id' => 'required',
            'district_id' => 'required',
            'area' => 'required',
            'area_type' => 'required',
            'price' => 'required',
            'price_type' => 'required',
            'description' => 'required',
            'images' => 'required',
        ];
        $validator = validateInput($input, $rules, []);
        if ($validator) {
            return $this->response
                ->json(CODE_NO_ACCESS, $validator->getMessageBag(), trans('messages.something_went_wrong'));
        }
        $input['status'] = Consignments::STATUS_TIEP_NHAN;
        $input['account_id'] = $this->account->id;
        $result = $this->model->create($input);
        if($result){
            return $this->response->json(CODE_SUCCESS, '', trans('messages.create_success'));
        }else{
            return $this->response->json(CODE_NO_ACCESS, '', trans('messages.create_failed'));
        }
    }

    public function update(){
        $input = $this->request->all();
        $rules = [
            'id' => 'required',
            'fullname' => 'required',
            'phone' => 'required',
            'email' => 'required',
            'title' => 'required',
            'product_type' => 'required',
            'land_type' => 'required',
            'address' => 'required',
            'city_id' => 'required',
            'district_id' => 'required',
            'area' => 'required',
            'area_type' => 'required',
            'price' => 'required',
            'price_type' => 'required',
            'description' => 'required',
        ];
        $validator = validateInput($input, $rules, []);
        if ($validator) {
            return $this->response
                ->json(CODE_NO_ACCESS, $validator->getMessageBag(), trans('messages.something_went_wrong'));
        }
        $consigment = $this->model->find($input['id']);
        $consigment->update($input);
        return $this->response->json(CODE_SUCCESS, '', trans('messages.update_success'));
    }

    public function delete(){

    }

    public function updateStatus()
    {
        $input = $this->request->all();
        $rules = [
            'id' => 'required',
        ];
        $validator = validateInput($input, $rules, []);
        if ($validator) {
            return $this->response
                ->json(CODE_NO_ACCESS, $validator->getMessageBag(), trans('messages.something_went_wrong'));
        }
        $consigment = $this->model->find($input['id']);
        $consigment->status = Consignments::STATUS_HUY;
        $consigment->save();
        return $this->response->json(CODE_SUCCESS, '', trans('messages.update_success'));
    }

    public function optionConsignment(){
        $data['product_type'] = OptionConsignments::where('type', OptionConsignments::PRODUCT_TYPE)->with('children')->get();
        $data['city']         = Province::with('district')->get();
        $data['area']         = OptionConsignments::where('type', OptionConsignments::AREA_TYPE)->get();
        $data['price_type']   = OptionConsignments::where('type', OptionConsignments::PRICE_TYPE)->get();
        return $this->response->json(CODE_SUCCESS, $data, '');
    }

}

app/Http/Controllers/Apis/Customers/CustomersController.php
<?php

namespace App\Http\Controllers\Apis\Customers;

use App\Http\Controllers\Apis\BaseApiController;
use App\Models\Customers\Customer;
use App\Services\ResponseService;
use Illuminate\Http\Request;

class CustomersController extends BaseApiController
{
    private $response;
    private $model;

    public function __construct(ResponseService $response) {
        $this->response = $response;
        $this->model    = new Customer();
    }

    public function getIndex(Request $request) {
        $input      = $request->all();
        $checkValidation =  $this->validateInput($input, ['page', 'number_record']);
        if($checkValidation) {
            return $checkValidation->content();
        }
        $name           = isset($input['name']) ? $input['name'] : '';
        $page           = $input['page'];
        $number_record  = isset($input['number_record']) ? $input['number_record'] : PAGINATE;
        $data_store     = $this->model->where('fullname',  'like', '%' . $name . '%')
                                      ->take($number_record)->skip(($page - 1) * $number_record)->get()->toArray();
        if(empty($data_store)) {
            $result = $this->response->api_json(false, $data_store, 'Không có dữ liệu trả về', 204);
        } else {
            $result = $this->response->api_json(true, $data_store, '', 200);
        }
        return $result;
    }

}

resources/views/administrator/customers/sharing/add_sharing.blade.php
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="row form-group m-2">
    <div class="col-md-6 col-lg-3">
        <label class="col-form-label">
            Tên chiến dịch
        </label>
    </div>
    <div class="col-md-6">
        <input type="text"
               name="name"
               class="form-control m-input"
               placeholder="Tên chiến dịch"
               value="{{old('name')}}"
        />
    </div>
</div>
<div class="m-wizard__form-step  repeater_customer_sharing"
     id="m_wizard_form_step_2">
    <div class="" data-repeater-list="list_user_sharing">
        <div class="row form-group border p-3 class-repeater-item m-0" data-repeater-item>
            <div class="col-md-3 align-self-center">
                <div class="row form-group">
                    <div class="col-md-6 col-lg-3">
                        <label class="col-form-label">
                            Số lượng
                        </label>
                    </div>
                    <div class="col-md-6">
                        <input type="number"
                               name="number_share"
                               class="form-control m-input"
                               id="number_share"
                               placeholder="Số lượng"
                        />
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="row form-group">
                    <div class="col-md-6 col-lg-3">
                        <label class="col-form-label">
                            Nhóm quyền
                        </label>
                    </div>
                    <div class="col-md-6 col-lg-8">
                        <select class="form-control m-input drl_roles"
                                name="role_id">
                            <option value="0">Tất cả</option>
                            @foreach ($listRoles as $key_l => $value_l)
                                <option value="{{ $key_l }}">
                                    {{ $value_l }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row form-group">
                    <div class="col-md-6 col-lg-3">
                        <label class="col-form-label">
                            User
                        </label>
                    </div>
                    <div class="col-md-6 col-lg-8">
                        <select class="form-control m-input slt_lst_user" name="user_id">
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-2 align-self-center">
                <button class="btn btn-primary" type="button"
                        data-repeater-delete
                        style="background-color:rgb(255,15,0);">
                    Xóa
                </button>
            </div>
        </div>
    </div>
    <div class="row d-inline-block float-right m-2">
        <div class="col">
            <button data-repeater-create class="btn btn-primary "
                    type="button">
                Thêm dòng
            </button>
        </div>
    </div>
</div>
<div class="row d-block m-2" style="clear: both">
    <div class="col-md-2">
        <input type="submit" value="Chia dữ liệu" class="btn btn-primary form-control"/>
    </div>
</div>
</form>

<script>
    $(document).ready(function () {
        initGetUserByRole();
        $('#customer_type').on('change', function () {
            initCountCustomer();
        });
        $('#customer_group').on('change', function () {
            initCountCustomer();
        });
    });

    function initGetUserByRole() {
        $('.drl_roles').on('change', function () {
            var that = this;
            var role_id = $(that).val();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: './sharing/user-by-role/' + role_id,
                cache: false,
                type: "post",
                processData: false,
                contentType: false,
                success: function (response) {
                    $(that).closest('.class-repeater-item').find('.slt_lst_user').empty();
                    $(that).closest('.class-repeater-item').find('.slt_lst_user').empty().append(response.data);
                },
                error: function (data) {

                }
            });

        })
    }

    function initCountCustomer() {
        var customer_type = $('#customer_type').val();
        var customer_group = $('#customer_group').val();
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            url: './sharing/count-customer',
            cache: false,
            type: "post",
            data: {cus_type: customer_type, cus_group: customer_group},
            success: function (response) {
                $('.totalRecord').text(response.data)
            },
            error: function (data) {

            }
        });
    }

</script>

resources/views/administrator/customers/sharing/index.blade.php
@extends('administrator.app')
@section('title','Danh sách khách hàng kho')

@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-content">
            <div class="m-portlet">

                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Chia khách hàng
                            </h3>
                        </div>
                    </div>
                </div>
                <!-- END: Subheader -->
                <div class="m-content">
                    <!--begin::Section-->
                    @include('administrator.errors.info-search')
                    <div class="m-section ">
                        @if(session('list-fail'))
                            <div class="alert alert-danger alert-notification">
                                @foreach (session('list-fail') as $element)
                                    {{ $element }}<br>
                                @endforeach
                            </div>
                        @endif
                        @include('administrator.errors.messages')
                        @include('administrator.customers.sharing.search')
                        @include('administrator.customers.sharing.add_sharing')
                    </div>
                    <!--end::Section-->
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/administrator/customers/sharing/list.blade.php
@extends('administrator.app')
@section('title','Danh sách chiến dịch')

@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-content">
            <div class="m-portlet">

                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Danh sách chiến dịch
                            </h3>
                        </div>
                    </div>
                </div>
                <!-- END: Subheader -->
                <div class="m-content">
                    <!--begin::Section-->
                    <div class="col-xs-12" style="margin-bottom: 20px">
                        <a href="{{ route('list.index') }}" class="btn btn-danger m-btn m-btn--icon">
                            <span>
                                <span>
                                    Danh sách khách hàng
                                </span>
                            </span>
                        </a>
                        <a href="{{ route('sharing.index') }}" class="btn btn-danger m-btn m-btn--icon">
                            <span>
                                <span>
                                    Chia khách hàng
                                </span>
                            </span>
                        </a>
                    </div>
                    @include('administrator.errors.info-search')
                    <div class="m-section ">
                        @if(session('list-fail'))
                            <div class="alert alert-danger alert-notification">
                                @foreach (session('list-fail') as $element)
                                    {{ $element }}<br>
                                @endforeach
                            </div>
                        @endif
                        @include('administrator.errors.messages')
                        <div class="m-section__content m-portlet m-portlet--mobile">
                            <div class="m_datatable" id="child_data_local"></div>
                        </div>
                    </div>
                    <!--end::Section-->
                </div>
            </div>
        </div>
    </div>
    @include('administrator.customers.sharing.script')
@stop

resources/views/administrator/customers/sharing/search.blade.php
{{ Form::open(array('route' => 'sharing.store', 'method' => 'POST', 'id' =>'customer-sharing')  ) }}
<div class="row gutter-2 gutter-lg-3 mb-4">
    <div class="col-md-3 col-sm-6 mb-3 mb-md-0 bold">
        <label>Nhóm khách hàng</label>
        {{ Form::select('group',
         ['' => 'Tất cả'] + $listCusGroup, old('group'),
          ['class' => 'form-control', 'id' => 'customer_group'])
          }}
    </div>
    <div class="col-md-2 col-sm-6 mb-3 mb-md-0 bold">
        <label>Loại khách hàng</label>
        {{ Form::select('type',
         [0 => 'Tất cả'] + $listCusType, old('type'),
          ['class' => 'form-control ', 'id' => 'customer_type'])
          }}
    </div>
    <div class="col-md-2 col-sm-6 mb-3 mb-md-0">
        <label>Danh sách chiến dịch</label>
        <a class="btn btn-primary" href="sharing/list">Danh sách chiến dịch</a>
    </div>
</div>
<div class="font-weight-bold">
    Tổng số khách hàng chưa chia: <span class="totalRecord">{{$totalRecord}}</span>
</div>