routes/web.php
        Route::resource('/dashboard', Administrators\Systems\DashboardController::class);
        Route::resource('branch', Systems\BranchesController::class);
        Route::resource('position', Systems\PositionsController::class);
        Route::get('user/user-department/{id}', 'Users\UsersController@getUserByDepartment')->name('user.list-user-by-department');
        Route::post('user/import', 'Users\UsersController@postImport')->name('user.import');
        Route::post('role/import', 'Permissions\RolesController@postImport')->name('role.import');
        Route::post('user/change-password', 'Users\UsersController@postChangePassword')->name('user.post-change-password');
        Route::get('/user/list', 'Users\UsersController@getList');
        Route::get('/user/change-password', 'Users\UsersController@getChangePassword')->name('user.get-change-password');
        Route::get('/user/be-managed', 'Users\UsersController@getBeManaged');
        Route::get('/user/search', 'Users\UsersController@getSearch');
        Route::get('user/student/edit-info', 'Users\EducationUserInfosController@index')->name('user.student.edit');
        Route::get('user/student/view-info/{id}', 'Users\EducationUserInfosController@viewInfo')->name('user.student.view');
        Route::get('user/student', 'Users\EducationUserController@index')->name('user.student');
        Route::get('user/teacher', 'Users\EducationUserController@getTeacher')->name('user.teacher');
        Route::get('user/teacher/view-info/{id}', 'Users\EducationUserInfosController@viewInfoTeacher')->name('user.teacher.view');
        Route::get('user/teacher/edit-info', 'Users\EducationUserInfosController@editInfoTeacher')->name('user.teacher.edit');
        Route::post('/user/{id}', 'Users\UsersController@destroy');
        Route::post('user/education-info/store', 'Users\EducationUserInfosController@store');
        Route::post('user/education-info/uploadavatar', 'Users\EducationUserInfosController@updateAvatar');
        Route::get('/user/read-notification/{id}', 'Users\UsersController@readNotification')->name('user.read.notification');
        Route::resource('user', Users\UsersController::class);
        Route::resource('department', Systems\DepartmentsController::class);
        Route::resource('company', Systems\CompaniesController::class);
        Route::resource('role', Permissions\RolesController::class);
        Route::resource('permission', Permissions\PermissionsController::class);
        Route::get('/config-role', 'Permissions\RolesController@getConfigRole')->name('role.config-role');
        Route::put('/put-permission', 'Permissions\RolesController@putPermissionIntoRole')->name('role.put-permission');
        Route::put('put-role', 'Permissions\RolesController@putRoleIntoUser')->name('role.put-role');
        Route::get('config-user', 'Permissions\RolesController@getConfigUser')->name('role.config-user');
        Route::get('config-role-user', 'Permissions\RolesController@getConfigRoleUser')->name('role.config-role-user');
        Route::post('config-role-user/store', 'Permissions\RolesController@postConfigRoleUser')->name('role.cf-role-user-store');
        Route::get('permission-by-role', 'Permissions\RolesController@getPermissionByRole');
        Route::resource('user-type', Users\TypesController::class);
    });
    Route::group(['prefix' => 'info'], function () {
        Route::post('/project/attachment', 'Projects\ProjectsController@postUploadAttachment')->name('project.upload-attachment');
        Route::get('/project/list', 'Projects\ProjectsController@getList');
        Route::post('/project/{id}', 'Projects\ProjectsController@update');
        Route::get('/project/delete/{id}', 'Projects\ProjectsController@destroy');
        Route::delete('/project/attachment', 'Projects\ProjectsController@postDeleteAttachment')->name('project.delete-attachment');
        Route::get('/project/city/{id}', 'Projects\ProjectsController@getDistrict');
        Route::resource('project-manager', Projects\ProjectManagersController::class);
        Route::resource('type', Projects\TypesController::class);
        Route::resource('segment', Projects\SegmentsController::class);
        Route::resource('project', Projects\ProjectsController::class);

        Route::resource('document-category', Projects\DocumentCategoriesController::class);
        Route::get('document/tree-data', 'Projects\DocumentsController@getTreeData')->name('document.tree-data');
        Route::get('document/upload/{id}', 'Projects\DocumentsController@getUpload')->name('document.upload');
        Route::resource('document', Projects\DocumentsController::class);
        Route::put('/news/accept/{id}', 'Projects\NewsController@putApprove')->name('news.approve');
    });
    Route::post('/upload', 'Administrators\Systems\UploadController@postUpload');

    Route::group(['prefix' => 'customer'], function () {
        Route::get('history/list/{id}', 'Customers\CustomersController@getHistoryToId')->name('customer.histories.list');
        Route::get('district/{id}', 'Customers\CustomersController@getDistrictOnCity')->name('city.district.list');
        Route::get('notification/call_back', 'Customers\CustomersController@listTimeCallBackCustomerOnday')->name('customer.notification.call_back');
        Route::get('project-by-sale/{id}', 'Customers\CustomersController@getProjectBySaleId')->name('customer.project.sale');
        // Thu hồi khách hàng
        Route::get('/list/{id}/collection-customer', 'Customers\CustomersController@collectionCustomer')->name('customer.collection-customer');
        Route::post('/list/{id}/update-collection-customer', 'Customers\CustomersController@updateCollectionCustomer')->name('customer.update-collection-customer');
        Route::get('/list/collection-customer', 'Customers\CustomerSharingUsersController@getCollectionCustomer')->name('customer.list-collection-customer');

        Route::get('upcoming/recover', 'Customers\CustomersController@getUpcomingRecover');
        Route::resource('list', Customers\CustomersController::class);
        Route::resource('level', Customers\LevelsController::class);
        Route::resource('customer_type', Customers\TypeCustomersController::class);
        Route::post('history/save', 'Customers\HistoriesController@saveHistory')->name('customer.history.save');
        Route::get('history/today/{type}', 'Customers\HistoriesController@getTodayCare');

        Route::get('/historyCus', 'Customers\CustomersController@historyCustomer')->name('customer.historyCus');
        Route::post('/getHistoryCus/{id}', 'Customers\CustomersController@getHistoryCustomer')->name('customer.getHistoryCus');
        Route::post('/showHistoryCus', 'Customers\CustomersController@showHistoryCustomer')->name('customer.showHistoryCus');

        Route::resource('history', Customers\HistoriesController::class);

        Route::get('/import', 'Customers\CustomersController@getImportForm')->name('customer.get-import');
        Route::post('/import', 'Customers\CustomersController@postImport')->name('customer.post-import');

        //giao thu contact
        Route::get('/share-customer-by-leader', 'Customers\CustomersController@getShareCustomerByLeader')->name('customer.get-share-customer-by-leader');
        Route::get('/get-total-customer-by-share/{id}', 'Customers\CustomersController@getTotalCustomerByShare')->name('customer.get-total-customer-by-share');
        Route::post('/share-customer-by-leader', 'Customers\CustomersController@postShareCustomerByLeader')->name('customer.post-share-customer-by-leader');


        Route::get('/import-store', 'Customers\CustomersController@getImportStoreForm')->name('customer_stores.get-import');
        Route::post('/import-store', 'Customers\CustomersController@postImportStore')->name('customer_stores.post-import');
        Route::get('/import-store/download-file', 'Customers\CustomersController@downloadFileImport')->name('customer_stores.download');
        Route::get('/stores', 'Customers\CustomersController@indexStores')->name('customer_stores.index');

        Route::post('/sharing/user-by-role/{id}', 'Customers\CustomerSharingsController@getUserByRole');
        Route::post('/sharing/count-customer', 'Customers\CustomerSharingsController@countCustomer');
        Route::get('/sharing/list', 'Customers\CustomerSharingsController@list')->name('sharing.list');
        Route::get('/sharing/sharing-user/{id}', 'Customers\CustomerSharingsController@getSharingUser')->name('sharing.list-user');
        Route::resource('sharing', Customers\CustomerSharingsController::class);
        Route::get('sharing-user/list-cus-share/{id}', 'Customers\CustomerSharingUsersController@listShare')->name('sharing-user.listShare');
        Route::get('sharing-user/list-cus-recovery/{id}', 'Customers\CustomerSharingUsersController@listRecovery')->name('sharing-user.listRecovery');
        Route::resource('sharing-user', Customers\CustomerSharingUsersController::class);


    });
    Route::get('fanpage', 'FacebooksController@getFanpage');
    Route::get('fanpage/post/{id}', 'FacebooksController@getPostByPage')->name('page.post');
    Route::get('fanpage/post/{id}/comments', 'FacebooksController@getCommentByPost')->name('page.post_comment');
    Route::get('fanpage/{pageId}/inbox', 'FacebooksController@getInboxByPage')->name('page.inbox');
    Route::get('fanpage/conversation/{conversationId}', 'FacebooksController@getConversationDetail')->name('page.conversation');

    Route::get('fanpage/find/{url}', 'FacebooksController@getPageByUrl');
    Route::get('fanpage/{pageId}/feed', 'FacebooksController@getFeedsByPage');
    Route::post('fanpage/{pageId}/feed', 'FacebooksController@postFeedToPage');
    Route::post('fanpage/post/{id}', 'FacebooksController@postCommentToPost');
    Route::get('fanpage/conversation/{conversationId}/reply', 'FacebooksController@postCommentToConversation');

app/Models/Projects/Advantages.php
<?php

namespace App\Models\Projects;

use Illuminate\Database\Eloquent\Model;

// class Advantages extends Model {

//     protected $table = 'project_advantages';

//     const KEYPOINT   = 'keypoint';
//     const PROJECT_ID = 'project_id';
//     const CREATED_BY = 'created_by';
//     const UPDATED_BY = 'updated_by';

//     /**
//      * The attributes that are mass assignable.
//      *
//      * @var array

//     protected $fillable = [
//         self::KEYPOINT,
//         self::PROJECT_ID,
//         self::CREATED_BY,
//         self::UPDATED_BY,
//     ];

//     public static function getFieldVietnamese() {
//         return [
//             self::KEYPOINT => trans('field.keypoint'),
//         ];
//     }

// }*/

app/Models/Projects/Attachment.php
<?php

namespace App\Models\Projects;

use Illuminate\Database\Eloquent\Model;

// class Attachment extends Model {

//     protected $table = 'project_attachments';

//     const NAME       = 'name';
//     const SIZE       = 'size';
//     const EXTENDSION = 'extendsion';
//     const URL        = 'url';
//     const FILE       = 'file';
//     const CREATED_BY = 'created_by';
//     const UPDATED_BY = 'updated_by';
//     const PROJECT_ID = 'project_id';

//     /**
//      * The attributes that are mass assignable.
//      *
//      * @var array
//      */
//     protected $fillable = [
//         self::NAME,
//         self::SIZE,
//         self::EXTENDSION,
//         self::URL,
//         self::PROJECT_ID,
//         self::CREATED_BY,
//         self::UPDATED_BY,
//     ];

//     public static function getFieldVietnamese() {
//         return [
//             self::NAME       => trans('field.name'),
//             self::SIZE       => trans('field.size'),
//             self::EXTENDSION => trans('field.extendsion'),
//             self::URL        => trans('field.url'),
//             self::PROJECT_ID => trans('field.project_id'),
//         ];
//     }

// }

app/Models/Projects/District.php
<?php

namespace App\Models\Projects;

use Illuminate\Database\Eloquent\Model;

class District extends Model {
    //
}

app/Http/Controllers/Apis/Projects/ProjectsController.php
<?php

namespace App\Http\Controllers\Apis\Projects;

use App\Models\Customers\Accounts;
use App\Models\Customers\FeedbackSale;
use App\Models\Projects\ProjectAccount;
use App\Models\Projects\ProjectManager;
use App\Models\Users\AccountTransactions;
use App\Models\Users\User;
use App\Services\AuthService;
use App\Services\ResponseService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Tymon\JWTAuth\JWTAuth;

class ProjectsController extends Controller
{

    private $request;

    private $response;

    private $model;

    private $account;

    public function __construct(Request $request, ProjectManager $model, ResponseService $response,JWTAuth $auth)
    {
        $this->request  = $request;
        $this->response = $response;
        $this->model    = $model;
        $this->account = Auth::guard('api')->user();
    }

    public function index(){
        $listProject    = ProjectAccount::join('project_managers', 'project_managers.id', '=', 'account_projects.project_id')
                        ->where('account_projects.account_id', Auth::guard('api')->user()->id)
                        ->whereNull('account_projects.deleted_at')
                        ->select('project_managers.id', 'name', 'image_url', 'hotline', 'email', 'description', 'rank_project', 'project_managers.created_at', 'project_managers.updated_at')
                        ->get();
        if($listProject->count() > 0){
            return $this->response->json(Response::HTTP_OK, $listProject, 'Danh sách dự án');
        }
        return $this->response->json(Response::HTTP_OK, $listProject, 'Chưa có dự án nào được cập nhật cho bạn');
    }

    public function postRankProject(){
        $listRule = [
            'id' => 'required',
            'rank_project' => 'required',
        ];
        $fieldVN = [
            'id' => 'ID dự án',
            'rank_project' => 'Xếp hạng dự án',
        ];

        $validator = validateInput($this->request->all(), $listRule, $fieldVN);
        if ($validator) {
            return $this->response->json(CODE_NO_ACCESS, $validator->getMessageBag(), 'Lỗi dữ liệu');
        }
        $projectAccount = ProjectAccount::where('account_id', $this->account->id)
                                        ->where('project_id', $this->request->get('id'))->first();
        if($projectAccount){
            $projectAccount->rank_project = $this->request->get('rank_project');
            $projectAccount->save();
            return $this->response->json(Response::HTTP_OK, '', 'Đánh giá dự án thành công');
        }else{
            return $this->response->json(CODE_NOT_FOUND, '', 'Dự án không tồn tại');
        }
    }

    public function getHistoryPayment(){
        $listRule = [ 'id' => 'required'];
        $fieldVN = [ 'id' => 'ID dự án'];
        $result = $this->validateInputApi($listRule, $fieldVN);
        if($result){
            return $result;
        }
        $data = AccountTransactions::where('account_id', $this->account->id)
            ->where('project_id', $this->request->id)
            ->where('parent_id', 0)->select('id', 'name')->with('children')->get();
        return $this->response->json(Response::HTTP_OK, $data, '');
    }

    //TODO chua lam xong
    public function listSaleProject(){
        $listRule = [ 'id' => 'required'];
        $fieldVN = [ 'id' => 'ID dự án'];
        $result = $this->validateInputApi($listRule, $fieldVN);
        if($result) {
            return $result;
        }
        $listSale = AccountTransactions::where('parent_id', 0)
                                    ->where('account_id', $this->account->id)
                                    ->where('project_id', $this->request->id)->get();
        $data = array();
        foreach ($listSale as $key => $value){

            $data[$key]['id'] = $value->sale->id;
            $data[$key]['transaction_id'] = $value->id;
            $data[$key]['fullname'] = $value->sale->fullname;
            $data[$key]['avatar'] = $value->sale->avatar;
            $data[$key]['name'] = $value->name ;
            $data[$key]['project_name'] = $value->project->name;
            $data[$key]['rank'] = 0;
            $totalRank = FeedbackSale::where('transaction_id', $value->id)->sum('rank_sale');
            if($totalRank > 0){
                $data[$key]['rank'] = round($totalRank / FeedbackSale::where('transaction_id', $value->id)->count());
            }
        }
        return $this->response->json(Response::HTTP_OK, $data, '');
    }

    public function postFeedBack(){
        $feedback['account_id']     = $this->account->id;
        $feedback['transaction_id'] = $this->request->transaction_id;
        $feedback['sale_id']        = $this->request->sale_id;
        $feedback['rank_sale']        = $this->request->rank_sale;
        $feedback['note']        = $this->request->note;
        $result = FeedbackSale::create($feedback);
        return $this->response->json(Response::HTTP_OK, $result, trans('messages.create_success'));
    }

    private function validateInputApi($listRule, $fieldVN){
        $validator = validateInput($this->request->all(), $listRule, $fieldVN);
        if ($validator) {
            return $this->response->json(CODE_NO_ACCESS, $validator->getMessageBag(), 'Lỗi dữ liệu');
        }
        if(isset($listRule['id'])){
            $checkProject = ProjectManager::find($this->request->id);
            if(!$checkProject){
                return $this->response->json(CODE_NOT_FOUND, '', 'Dự án không tồn tại');
            }
        }
        return false;
    }
}

resources/views/administrator/projects/document-category/create-bak.blade.php
@extends('administrator.app')
@section('title','Thư mục')

@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
	<!-- BEGIN: Subheader -->
	<div class="m-subheader">
	    <div class="d-flex align-items-center">
	        <div class="mr-auto">
	            <h3 class="m-subheader__title m-subheader__title--separator">
	                Thư mục
	            </h3>
	            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
	                <li class="m-nav__item m-nav__item--home">
	                    <a href="#" class="m-nav__link m-nav__link--icon">
	                        <i class="m-nav__link-icon la la-home"></i>
	                    </a>
	                </li>
	            </ul>
	        </div>
	    </div>
	</div>
	<!-- END: Subheader -->
	<div class="m-content">
		<div class="row">
			<div class="col-md-12" style="margin-bottom: 20px">
				<a href="{{ route('document-category.index') }}" class="btn btn-success">Danh sách thư mục</a>
			</div>
	        <div class="col-md-12">
				@include('administrator.errors.errors-validate')
	            <!--begin::Portlet-->
	            <div class="m-portlet m-portlet--tab">
	                <div class="m-portlet__head">
	                    <div class="m-portlet__head-caption">
	                        <div class="m-portlet__head-title">
	                            <span class="m-portlet__head-icon m--hide">
	                                <i class="la la-gear"></i>
	                            </span>
	                            <h3 class="m-portlet__head-text">
	                                Thêm mới thư mục
	                            </h3>
	                        </div>
	                    </div>
	                </div>
	                {{ Form::open(array('route' => 'document-category.store', 'class' => 'm-form m-form--fit m-form--label-align-right')) }}
	                    <div class="m-portlet__body">
	                        <div class="form-group m-form__group">
	                            <label for="name">
	                                Tên
	                            </label>
	                            <input type="name" class="form-control m-input" id="name" placeholder="Tên vị trí" name="name" value="{{ old('name') }}">
	                        </div>
	                    </div>
	                    <div class="m-portlet__foot m-portlet__foot--fit">
	                        <div class="m-form__actions">
	                            <button class="btn btn-primary">
	                                Lưu
	                            </button>
	                            <a class="btn btn-secondary" href="{{ route('document-category.index') }}">
	                                Trở về danh sách
	                            </a>
	                        </div>
	                    </div>
	                {{-- </form> --}}
	                {{ Form::close() }}
	            </div>
	            <!--end::Portlet-->
	        </div>
	        <!--end::Form-->
	    </div>
	</div>
</div>
@stop

resources/views/administrator/projects/document-category/edit-bak.blade.php
@extends('administrator.app')
@section('title','Thư mục')

@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                    Thư mục
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <div style="margin-bottom: 20px">
            <a href="{{ route('document-category.index') }}" class="btn btn-success">Danh sách thư mục</a>
        </div>
        <div class="row">
            <div class="col-md-12">
                @include('administrator.errors.errors-validate')
                <!--begin::Portlet-->
                <div class="m-portlet m-portlet--tab">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Cập nhật thư mục
                                </h3>
                            </div>
                        </div>
                    </div>
                    {{ Form::open(array('route' => array('document-category.update', $data->id), 'method' => 'PUT', 'class' => 'm-form m-form--fit m-form--label-align-right')) }}
                        <div class="m-portlet__body">
                            <div class="form-group m-form__group">
                                <label for="name">
                                    Tên
                                </label>
                                <input type="name" class="form-control m-input" id="name" placeholder="Tên vị trí" name="name" value="{{ $data->name }}">
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__foot--fit">
                            <div class="m-form__actions">
                                <button class="btn btn-primary">
                                    Lưu
                                </button>
                                <a class="btn btn-secondary" href="{{ route('document-category.index') }}">
                                    Trở về danh sách
                                </a>
                            </div>
                        </div>
                    {{-- </form> --}}
                    {{ Form::close() }}
                </div>
                <!--end::Portlet-->
            </div>
            <!--end::Form-->
        </div>
    </div>
</div>
@stop

resources/views/administrator/projects/document-category/index-bak.blade.php
@extends('administrator.app')
@section('title','Thư mục tài liệu')

@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                    Thư mục tài liệu
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <!--begin::Section-->
        <div class="col-xs-12" style="margin-bottom: 20px">
            <a href="{{ route('document-category.create') }}" class="btn btn-primary m-btn m-btn--icon">
                <span>
                    <i class="fa flaticon-plus"></i>
                    <span>
                        Thêm mới
                    </span>
                </span>
            </a>
        </div>
        @include('administrator.errors.info-search')
        <div class="m-section">
            @include('administrator.errors.messages')
            <div class="m-section__content">
                <table class="table m-table m-table--head-bg-warning">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Tên
                            </th>
                            <th>
                                Tùy chọn
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($data as $key => $value)
                        <tr>
                            <th scope="row">
                                {{ $key + 1 }}
                            </th>
                            <td>
                                {{ $value['name'] }}
                            </td>
                            <td>
                                <a href="{{ route('document-category.edit', $value->id) }}" class="btn btn-accent m-btn m-btn--icon m-btn--icon-only">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                {{ Form::open(array('method'=>'DELETE', 'route' => array('document-category.destroy', $value->id), 'style' => 'display: inline-block;')) }}
                                <button onclick="return confirm('Bạn có chắc chắn muốn xóa?');" class="btn btn-danger m-btn m-btn--icon m-btn--icon-only">
                                    <i class="fa fa-close"></i>
                                </button>
                                {{ Form::close() }}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            {{ $data->links() }}
            Tổng số {{ $data->total() }} bản ghi
        </div>
        <!--end::Section-->
    </div>
</div>
@stop